project_name: BookTr
builds:
  - main: ./cmd/BookTr/
    binary: booktr
    id: default
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm

nfpms:
  - maintainer: aceberg <aceberg_a@proton.me>
    description: Translate texts side-by-side using LibreTranslate API
    homepage: https://github.com/aceberg/BookTr
    license: MIT
    section: utils
    formats:
    - deb
    - rpm
    - apk
    - termux.deb
    contents:
    - src: ./configs/BookTr.service
      dst: /lib/systemd/system/BookTr.service
    - src: ./configs/BookTr@.service
      dst: /lib/systemd/system/BookTr@.service
    scripts:
      postinstall: ./configs/postinstall.sh

archives:
  - files:
    - LICENSE
    - src: ./configs/BookTr.service
      dst: BookTr.service
    - src: ./configs/BookTr@.service
      dst: BookTr@.service
    - src: ./configs/install.sh
      dst: install.sh
    wrap_in_directory: true
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: "checksums.txt"
