basePath: /
definitions:
  models.Board:
    properties:
      Columns:
        items:
          $ref: '#/definitions/models.Column'
        type: array
      ID:
        type: integer
      Name:
        type: string
    type: object
  models.BoardInfo:
    properties:
      ID:
        type: integer
      Name:
        type: string
    type: object
  models.Card:
    properties:
      ColumnID:
        type: integer
      DateCreated:
        type: string
      DateMoved:
        type: string
      ID:
        type: integer
      Name:
        type: string
      Sort:
        type: integer
      Theme:
        type: string
    type: object
  models.Column:
    properties:
      BoardID:
        type: integer
      Cards:
        items:
          $ref: '#/definitions/models.Card'
        type: array
      Fold:
        type: boolean
      ID:
        type: integer
      Name:
        type: string
      Props:
        $ref: '#/definitions/models.ColumnProps'
      Sort:
        type: integer
    type: object
  models.ColumnProps:
    properties:
      ColumnID:
        type: integer
      GroupByDate:
        type: boolean
      ID:
        type: integer
      ShowDateCr:
        type: boolean
      ShowDateMv:
        type: boolean
      ShowID:
        type: boolean
    type: object
  models.Conf:
    properties:
      ConfPath:
        type: string
      DBPath:
        type: string
      DirPath:
        type: string
      Host:
        type: string
      Port:
        type: string
    type: object
info:
  contact:
    url: https://github.com/aceberg/FunBoard
  description: API built with Fiber v2
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: FunBoard API
  version: "1.0"
paths:
  /api/board:
    post:
      consumes:
      - application/json
      description: Edit existing Board by ID or add new Board (if ID=0)
      parameters:
      - description: Board
        in: body
        name: board
        required: true
        schema:
          $ref: '#/definitions/models.Board'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "404":
          description: Not Found
      summary: Edit or add Board
      tags:
      - board
  /api/board/{id}:
    get:
      consumes:
      - application/json
      description: Get Board details by its unique ID
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Board'
        "404":
          description: Not Found
      summary: Get Board by ID
      tags:
      - board
  /api/board/del/{id}:
    get:
      consumes:
      - application/json
      description: Delete Board by ID
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "404":
          description: Not Found
      summary: Delete Board by ID
      tags:
      - board
  /api/boards:
    get:
      consumes:
      - application/json
      description: Get IDs and Names of all Boards
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.BoardInfo'
            type: array
        "404":
          description: Not Found
      summary: Get all Boards
      tags:
      - board
  /api/card:
    post:
      consumes:
      - application/json
      description: Edit existing Card by ID or add new Card (if ID=0)
      parameters:
      - description: Card
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/models.Card'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "404":
          description: Not Found
      summary: Edit or add Card
      tags:
      - card
  /api/card/del/{id}:
    get:
      consumes:
      - application/json
      description: Delete Card by ID
      parameters:
      - description: Card ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "404":
          description: Not Found
      summary: Delete Card by ID
      tags:
      - card
  /api/column:
    post:
      consumes:
      - application/json
      description: Edit existing Column by ID or add new Column (if ID=0)
      parameters:
      - description: Column
        in: body
        name: column
        required: true
        schema:
          $ref: '#/definitions/models.Column'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "404":
          description: Not Found
      summary: Edit or add Column
      tags:
      - column
  /api/column/del/{id}:
    get:
      consumes:
      - application/json
      description: Delete Column by ID
      parameters:
      - description: Column ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "404":
          description: Not Found
      summary: Delete Column by ID
      tags:
      - column
  /api/column/props:
    post:
      consumes:
      - application/json
      description: Edit Column Properties
      parameters:
      - description: Column Props
        in: body
        name: props
        required: true
        schema:
          $ref: '#/definitions/models.ColumnProps'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "404":
          description: Not Found
      summary: Edit Column Properties
      tags:
      - column
  /api/conf:
    get:
      consumes:
      - application/json
      description: Get app Config
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Conf'
        "404":
          description: Not Found
      summary: Get app Config
      tags:
      - config
    post:
      consumes:
      - application/json
      description: Save app Config
      parameters:
      - description: App config
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/models.Conf'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      summary: Save app Config
      tags:
      - config
swagger: "2.0"
